version: '2'

services:
    db:
        image: postgres:11.2
        volumes:
            - "./var/data/db-pg:/var/lib/postgresql/data"
        environment:
            POSTGRES_DB: ${POSTGRES_DATABASE}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        networks:
            - network
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./var/logs/symfony:/var/www/symfony/app/logs
        networks:
            - network
    nginx:
        build: nginx
        ports:
            - ${SYMFONY_APP_PORT}:80
        volumes_from:
            - php
        volumes:
            - ./var/logs/nginx/:/var/log/nginx
        networks:
          - network
    adminer:
        image: adminer
        restart: always
        ports:
            - ${DB_ADMIN_PORT}:8080
        networks:
            - network
    rabbit:
        image: rabbitmq:3.7-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - network

networks:
    network:
        driver: bridge
