services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\PaymentGateway\Domain\Usecase\RegisterPayment:
    App\PaymentGateway\Domain\Usecase\ProcessPayment:
    App\PaymentGateway\Domain\Usecase\CompletePayment:
    App\PaymentGateway\Domain\Usecase\CallbackPayment:

doctrine:
    orm:
        mappings:
            PaymentGateway:
                type: xml
                dir: '%kernel.project_dir%/src/PaymentGateway/Infrastructure/Doctrine/mappings'
                prefix: 'App\PaymentGateway\Domain\Model'
