services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\PaymentGateway\Domain\Usecase\RegisterPayment:
    App\PaymentGateway\Domain\Usecase\ProcessPayment:
    App\PaymentGateway\Domain\Usecase\CallbackPayment:
