services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Gateways selection
    App\PaymentGateway\Domain\Usecase\GatewaySelection\GatewaySelection:
        calls:
            - method: registerGatewayFactory
              arguments:
                  $gatewayFactory: '@gateway.factory.dotpay'
                  $predicates:
                      - '@gateway.predicate.byPaymentType.transfer'

    gateway.predicate.byPaymentType.transfer:
        class: App\PaymentGateway\Domain\Usecase\GatewaySelection\Predicate\ByPaymentType
        arguments: ['transfer']

    # Gateways configs
    gateway.factory.dotpay:
        class: App\PaymentGateway\Gateway\Dotpay\GatewayFactory
        arguments:
            $gatewayId: 'dotpay'
            $params:
                accountId: '%env(GATEWAY_DOTPAY_ACCOUNT_ID)%'
                pid: '%env(GATEWAY_DOTPAY_PIN)%'
                type: '4'
                action: 'https://ssl.dotpay.pl/test_payment/'
                lang: 'pl'
                apiVersion: 'dev'
                channel: 0
                channel_groups: 'K,T,P'
