#index:
#    path: /
#    controller: App\Controller\DefaultController::index

gateway.payment.request:
    controller: 'App\PaymentGateway\Delivery\Controller\ProcessPaymentController:processPayment'
    path: /payment/{paymentId}/process

gateway.payment.callback:
    controller: 'App\PaymentGateway\Delivery\Controller\PaymentRequestController:paymentRequest'
    path: /payment/{paymentId}/callback
