#index:
#    path: /
#    controller: App\Controller\DefaultController::index

gateway.payment.register:
    controller: 'App\PaymentGateway\Delivery\Controller\RegisterPaymentController:registerPayment'
    methods: POST
    path: /payment
    defaults: { _format: json }

gateway.payment.request:
    controller: 'App\PaymentGateway\Delivery\Controller\ProcessPaymentController:processPayment'
    methods: GET
    path: /payment/{paymentId}/process
    defaults: { _format: json }

gateway.payment.callback:
    controller: 'App\PaymentGateway\Delivery\Controller\PaymentRequestController:paymentRequest'
    path: /payment/{paymentId}/callback
