#index:
#    path: /
#    controller: App\Controller\DefaultController::index

gateway.payment.getstatus:
    controller: 'App\PaymentGateway\Delivery\Controller\GetPaymentStatusController:getStatus'
    methods: GET
    path: /api/payment/{paymentId}/status
    defaults: { _format: json }

gateway.payment.register:
    controller: 'App\PaymentGateway\Delivery\Controller\RegisterPaymentController:registerPayment'
    methods: POST
    path: /api/payment
    defaults: { _format: json }

gateway.payment.process:
    controller: 'App\PaymentGateway\Delivery\Controller\ProcessPaymentController:processPayment'
    methods: GET
    path: /api/payment/{paymentId}/process
    defaults: { _format: json }

gateway.payment.callback:
    controller: 'App\PaymentGateway\Delivery\Controller\CallbackPaymentController:callbackPayment'
    path: /api/payment/{paymentId}/callback
    methods: POST|GET
