#index:
#    path: /
#    controller: App\Controller\DefaultController::index

gateway.payment.request:
    controller: 'App\PaymentGateway\Delivery\Controller\PaymentRequestController:paymentRequest'
    path: /paymentRequest
