imports:
    - payment-gateway/**/*

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

#    App\:
#        resource: '../src/*'
#        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

#    App\PaymentGateway\:
#        resource: '../src/PaymentGateway/*'
#        exclude: '../src/PaymentGateway/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

#    App\PaymentGateway\Delivery\Controller\:
#        resource: '../src/PaymentGateway/Delivery/Controller'
#        tags: ['controller.service_arguments']
#
#    App\PaymentGateway\Domain\Usecase\ProcessPayment:
