version: '3.4'

services:
  app:
    image: cloud.canister.io:5000/nowinypl/nowiny-payment-service:${APP_VERSION}
    env_file:
      - docker/.env.prod
    restart: unless-stopped
    volumes:
      - ./logs/app:/app/var/log
      - ./sessions:/app/var/sessions
    ports:
      - ${APP_PORT}:80

networks:
  default:
    driver: bridge
