version: '3.4'

services:
  app:
    build:
      context: ..
      target: app-dev
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    volumes:
      - ../app:/app
    env_file:
      - .env.local

  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
    volumes:
      - "./var/data/postgres:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    networks:
      - default

  rabbit:
    image: rabbitmq:3.7-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./var/rabbitmq/data:/var/lib/rabbitmq
    hostname: rabbit_node_1

networks:
  default:
    driver: bridge
