services:
  monolog_line_formatter:
    class: Monolog\Formatter\LineFormatter
    arguments:
      - "[%%datetime%%] [%%extra.request_id%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"

monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: error
      handler: file
      excluded_404s:
        # regex: exclude all 404 errors from the logs
        - ^/
    file:
      formatter: monolog_line_formatter
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      max_files: 10
      level: info
      channels: ["!php", "!event", "!doctrine"]
#        console:
#            type: console
#            process_psr_3_messages: false
#            channels: ["!event", "!doctrine"]
#        deprecation:
#            type: stream
#            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
#        deprecation_filter:
#            type: filter
#            handler: deprecation
#            max_level: info
#            channels: ["php"]
