services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
        tags: ['serializer.normalizer']

    Symfony\Component\Serializer\Normalizer\DateTimeNormalizer:
        tags: ['serializer.normalizer']
